// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormValidatorController from "./form_validator_controller"
import GridsterController from "./gridster_controller"
import ModalController from "./modal_controller"
import TooltipController from "./tooltip_controller"
import TurboController from "./turbo_controller"

application.register("form-validator", FormValidatorController)
application.register("gridster", GridsterController)
application.register("modal", ModalController)
application.register("tooltip", TooltipController)
application.register("turbo", TurboController)
